(defproject wonderful-lib "0.0.1-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License - v 1.0"
            :url "http://www.eclipse.org/legal/epl-v10.html"
            :distribution :repo}

  ;; I've changed the repl-options because the long compile time
  :repl-options {:timeout 120000}

  :min-lein-version "2.2.0"

  ;; We need to add src/cljs too, because cljsbuild does not add its
  ;; source-paths to the project source-paths
  :source-paths ["src/clj" "src/cljs"]


  :dependencies [[org.clojure/clojure "1.5.1"]
                 [org.clojure/clojurescript "0.0-2138"]
                 [org.clojure/core.async "0.1.267.0-0d7780-alpha"]]

  :plugins [[lein-cljsbuild "1.0.1"]]

  ;; Hooks the cljsbuild subtasks to the lein tasks: lein clean, lein
  ;; compile, lein test and lein jar
  :hooks [leiningen.cljsbuild]

  ;; Lein-cljsbuild plugin configuration. Here we define one build
  ;; only: the one used for packaging any cljs sources in the jar
  ;; generated by lein jar command
  :cljsbuild
  {:builds {;; This build is only used for including any cljs source
            ;; in the packaged jar when you issue lein jar command and
            ;; any other command that depends on it
            :useless
            {;; The dir pathnames where cljs sources live. Do not
             ;; include here any cljs source which is only used during
             ;; development or testing
             :source-paths ["src/cljs"]
             ;; The :jar true option is not needed to include the CLJS
             ;; sources in the packaged jar. This is because we added
             ;; the CLJS source codebase to the Leiningen
             ;; :source-paths

             ;:jar true
             ;; Compilation Options
             :compiler
             {;; The JS file pathname emitted by the compiler
              :output-to "dev-resources/public/js/useless.js"
              ;; Compiler optimizations option set to :none to speed
              ;; up this useless compilation
              :optimizations :none
              ;; No need to prettify the emitted js file
              :pretty-print false}}}})
